controller_manager:
  ros__parameters:
    update_rate: 30

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

      joints:
        - wheel_left_joint
        - wheel_right_joint

      command_interfaces:
        - velocity

      state_interfaces:
        - position
        - velocity

      state_publish_rate: 50.0
      command_publish_rate: 50.0

      allow_partial_joints_goal: true
      constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.01
        wheel_left_joint:
          trajectory: 0.1
          goal: 0.1
        wheel_right_joint:
          trajectory: 0.1
          goal: 0.1