controller_manager:
  ros__parameters:
    update_rate: 80

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity