joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - wheel_left_joint
      - wheel_right_joint
    command_interfaces:
      - velocity            # position·effort 가능
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    gains:
      wheel_left_joint:
        p: 0.0
        i: 0.0
        d: 0.0
        ff_velocity_scale: 1.0
      wheel_right_joint:
        p: 0.0
        i: 0.0
        d: 0.0
        ff_velocity_scale: 1.0